affinity: /Users/mfamili/work/datasets/affinity.csv
batch: 128
beta: 1
beta_cycle: 3
beta_load: null
beta_min: 0
beta_ratio: 0.5
channels: 8
classes: classes.csv
config_file: /Users/mfamili/work/test_affinity_merge/mixed_rot/avae-test-config.yml
cyc_method_beta: cycle_sigmoid
cyc_method_gamma: cycle_sigmoid
datapath: /Users/mfamili/work/datasets/shrec21_full_dataset/single_particles/
datatype: mrc
depth: 4
dynamic: true
epochs: 2000
eval: false
freq_acc: 10
freq_all: null
freq_con: 10
freq_dis: 10
freq_emb: 10
freq_eval: 10
freq_int: 10
freq_pos: 10
freq_rec: 10
freq_sim: 10
freq_sta: 10
gamma: 0.01
gamma_cycle: 3
gamma_load: null
gamma_min: 0
gamma_ratio: 0.5
gaussian_blur: false
gpu: true
latent_dims: 32
learning: 1.0e-06
limit: null
loss_fn: MSE
meta: null
model: a
no_val_drop: true
normalise: false
opt_method: adam
pose_dims: 6
restart: false
shift_min: false
split: 10
state: null
vis_acc: true
vis_aff: false
vis_all: true
vis_con: false
vis_cyc: true
vis_dis: true
vis_emb: true
vis_his: false
vis_int: true
vis_los: true
vis_pos: true
vis_rec: true
vis_sim: false
