#### Data parameters

datapath: data/shrec21_full_dataset/subtomo_files
affinity: data/shrec21_full_dataset/subtomo_files/affinity.csv
classes: data/shrec21_full_dataset/subtomo_files/classes.csv
limit: 1000
split: 20

#### Network parameters

depth:  3
channels:  64
latent_dims:  8
pose_dims: 1
model: a

#### Training parameters

no_val_drop: true
epochs:  1000
batch:  128
learning:  0.001
gpu:  true
freq_sta: None  # frequency of state saves

#### Loss parameters

beta:  1
gamma:  2
loss_fn:  MSE

#### Evaluation parameters
eval:  false
freq_eval: None # frequency of test evaluation (if test present)

#### Visualization parameters
vis_los:  true  # loss on/off (every epoch from epoch 2)
vis_acc:  true  # confusion matrices on/off
vis_rec:  true  # reconstructions on/off
vis_emb:  true  # latent embeddings on/off
vis_int:  true  # latent interpolations on/off
vis_dis:  true  # latent disentanglement on/off
vis_pos:  true  # pose disentanglement on/off
vis_his:  true  # class distribution histogram on/off
vis_all:  true  # sets all above to on/off
dynamic: true   # dynamic embedding visualisations on/off (freq same as freq_emb)

freq_acc: None  # frequency of accuracy visualisation
freq_rec: None  # frequency of reconstruction visualisation
freq_emb: None  # frequency of latent embedding visualisation
freq_int: None  # frequency of latent interpolation visualisation
freq_dis: None  # frequency of latent disentanglement visualisation
freq_pos: None  # frequency of pose disentanglement visualisation
freq_all: None  # sets all above to the same value (inc freq_sta and freq_eval)
